const { Router } = require("express");
const r = Router();
const c = require("../controller/Ordercontroller");
const { protect, admin } = require("../middleware/Auth");
r.post("/create-razorpay-order", protect, c.createRazorpayOrder);
r.post("/verify-payment",        protect, c.verifyPayment);
r.get("/my",                     protect, c.getMyOrders);
r.get("/stats",                  protect, admin, c.adminStats);
r.get("/all",                    protect, admin, c.adminGetOrders);
r.get("/:id",                    protect, c.getOrder);
r.put("/:id/status",             protect, admin, c.updateOrderStatus);
module.exports = r;