const { Router } = require("express");
const r = Router();
const c = require("../controller/Productcontroller");
const { protect, admin } = require("../middleware/Auth");
r.get("/",          c.getProducts);
r.get("/admin/all", protect, admin, c.adminGetProducts);
r.post("/",         protect, admin, c.createProduct);
r.get("/:id",       c.getProduct);
r.put("/:id",       protect, admin, c.updateProduct);
r.delete("/:id",    protect, admin, c.deleteProduct);
r.post("/:id/review", protect, c.addReview);
module.exports = r;