// scripts/seedProducts.js
// Run with: node scripts/seedProducts.js
require("dotenv").config();
const mongoose = require("mongoose");
const Product  = require("../model/Product"); // adjust path if needed

const MONGO_URI = process.env.MONGO_URI || "mongodb://localhost:27017/ecommerce";

const electronics = [
  {
    name: "Sony WH-1000XM5 Headphones",
    brand: "Sony",
    category: "Electronics",
    price: 29990,
    originalPrice: 34990,
    stock: 20,
    featured: true,
    description: "Industry-leading noise cancelling headphones with 30-hour battery life and crystal clear call quality.",
    images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80"],
    rating: 4.8,
    numReviews: 245,
    isActive: true,
  },
  {
    name: "Apple AirPods Pro (2nd Gen)",
    brand: "Apple",
    category: "Electronics",
    price: 24900,
    originalPrice: 26900,
    stock: 35,
    featured: true,
    description: "Active Noise Cancellation, Adaptive Transparency, and Personalised Spatial Audio.",
    images: ["https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=600&q=80"],
    rating: 4.7,
    numReviews: 189,
    isActive: true,
  },
  {
    name: "ASUS ROG Gaming Laptop",
    brand: "ASUS",
    category: "Electronics",
    price: 89990,
    originalPrice: 99990,
    stock: 8,
    featured: true,
    description: "RTX 4070, Intel i9, 16GB RAM, 1TB SSD. Built for elite gaming performance.",
    images: ["https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&q=80"],
    rating: 4.6,
    numReviews: 92,
    isActive: true,
  },
  {
    name: "Samsung 4K OLED Smart TV 55\"",
    brand: "Samsung",
    category: "Electronics",
    price: 74990,
    originalPrice: 84990,
    stock: 12,
    featured: false,
    description: "Quantum HDR OLED, 120Hz refresh rate, built-in Alexa and Google Assistant.",
    images: ["https://images.unsplash.com/photo-1593784991095-a205069470b6?w=600&q=80"],
    rating: 4.5,
    numReviews: 134,
    isActive: true,
  },
  {
    name: "Canon EOS R50 Mirrorless Camera",
    brand: "Canon",
    category: "Electronics",
    price: 59990,
    originalPrice: 64990,
    stock: 15,
    featured: false,
    description: "24.2MP APS-C sensor, 4K video, Wi-Fi & Bluetooth, perfect for content creators.",
    images: ["https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&q=80"],
    rating: 4.7,
    numReviews: 67,
    isActive: true,
  },
  {
    name: "iPad Pro 12.9\" M2 Chip",
    brand: "Apple",
    category: "Electronics",
    price: 99900,
    originalPrice: 109900,
    stock: 10,
    featured: true,
    description: "Liquid Retina XDR display, M2 chip, 5G connectivity, Apple Pencil support.",
    images: ["https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&q=80"],
    rating: 4.9,
    numReviews: 213,
    isActive: true,
  },
  {
    name: "JBL Flip 6 Bluetooth Speaker",
    brand: "JBL",
    category: "Electronics",
    price: 9999,
    originalPrice: 12999,
    stock: 50,
    featured: false,
    description: "Portable waterproof speaker with 12-hour playtime, bold JBL Pro Sound.",
    images: ["https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&q=80"],
    rating: 4.5,
    numReviews: 312,
    isActive: true,
  },
  {
    name: "OnePlus 12 5G Smartphone",
    brand: "OnePlus",
    category: "Electronics",
    price: 64999,
    originalPrice: 69999,
    stock: 25,
    featured: false,
    description: "Snapdragon 8 Gen 3, 50MP Hasselblad camera, 100W SUPERVOOC charging.",
    images: ["https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&q=80"],
    rating: 4.6,
    numReviews: 178,
    isActive: true,
  },
  {
    name: "Logitech MX Master 3S Mouse",
    brand: "Logitech",
    category: "Electronics",
    price: 7995,
    originalPrice: 9995,
    stock: 40,
    featured: false,
    description: "8K DPI precision sensor, quiet clicks, ergonomic design for all-day comfort.",
    images: ["https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&q=80"],
    rating: 4.8,
    numReviews: 421,
    isActive: true,
  },
  {
    name: "Dell 27\" 4K USB-C Monitor",
    brand: "Dell",
    category: "Electronics",
    price: 44990,
    originalPrice: 52990,
    stock: 18,
    featured: false,
    description: "4K UHD IPS display, USB-C 90W charging, perfect for professionals.",
    images: ["https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&q=80"],
    rating: 4.7,
    numReviews: 98,
    isActive: true,
  },
];

const clothing = [
  {
    name: "Classic White Oxford Shirt",
    brand: "Marks & Spencer",
    category: "Clothing",
    price: 1499,
    originalPrice: 2499,
    stock: 60,
    featured: true,
    description: "Premium 100% cotton oxford shirt, slim fit, perfect for office and casual wear.",
    images: ["https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600&q=80"],
    rating: 4.4,
    numReviews: 156,
    isActive: true,
  },
  {
    name: "Women's Floral Maxi Dress",
    brand: "Zara",
    category: "Clothing",
    price: 2799,
    originalPrice: 3999,
    stock: 30,
    featured: true,
    description: "Flowing chiffon fabric with vibrant floral print, midi length, adjustable straps.",
    images: ["https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&q=80"],
    rating: 4.6,
    numReviews: 89,
    isActive: true,
  },
  {
    name: "Slim Fit Denim Jeans",
    brand: "Levi's",
    category: "Clothing",
    price: 2499,
    originalPrice: 3499,
    stock: 75,
    featured: false,
    description: "512 slim taper fit, authentic stretch denim, classic 5-pocket styling.",
    images: ["https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&q=80"],
    rating: 4.5,
    numReviews: 234,
    isActive: true,
  },
  {
    name: "Men's Puffer Jacket",
    brand: "H&M",
    category: "Clothing",
    price: 3499,
    originalPrice: 4999,
    stock: 22,
    featured: false,
    description: "Lightweight water-resistant puffer, stand-up collar, side pockets.",
    images: ["https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&q=80"],
    rating: 4.3,
    numReviews: 112,
    isActive: true,
  },
  {
    name: "Yoga Leggings High Waist",
    brand: "Adidas",
    category: "Clothing",
    price: 1999,
    originalPrice: 2799,
    stock: 45,
    featured: true,
    description: "Climalite fabric, 4-way stretch, moisture-wicking, perfect for yoga and gym.",
    images: ["https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=600&q=80"],
    rating: 4.7,
    numReviews: 198,
    isActive: true,
  },
  {
    name: "Oversized Graphic Hoodie",
    brand: "Nike",
    category: "Clothing",
    price: 2999,
    originalPrice: 3999,
    stock: 38,
    featured: false,
    description: "Heavy-blend fleece, kangaroo pocket, oversized fit for streetwear style.",
    images: ["https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=600&q=80"],
    rating: 4.5,
    numReviews: 167,
    isActive: true,
  },
  {
    name: "Formal Blazer Charcoal Grey",
    brand: "Raymond",
    category: "Clothing",
    price: 5999,
    originalPrice: 7999,
    stock: 20,
    featured: false,
    description: "Single-breasted, notch lapel, wool blend, tailored fit for formal occasions.",
    images: ["https://images.unsplash.com/photo-1594938298603-c8148c4b4cc4?w=600&q=80"],
    rating: 4.6,
    numReviews: 74,
    isActive: true,
  },
  {
    name: "Women's Crop Top Set",
    brand: "Puma",
    category: "Clothing",
    price: 1799,
    originalPrice: 2499,
    stock: 55,
    featured: false,
    description: "Sports crop top & high-waist shorts set, breathable mesh panels.",
    images: ["https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&q=80"],
    rating: 4.4,
    numReviews: 143,
    isActive: true,
  },
  {
    name: "Ethnic Kurta Pajama Set",
    brand: "Fabindia",
    category: "Clothing",
    price: 2199,
    originalPrice: 2999,
    stock: 28,
    featured: false,
    description: "Handwoven cotton kurta with matching pajama, block print design.",
    images: ["https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?w=600&q=80"],
    rating: 4.5,
    numReviews: 88,
    isActive: true,
  },
  {
    name: "Running Shoes Air Cushion",
    brand: "Nike",
    category: "Clothing",
    price: 6999,
    originalPrice: 8999,
    stock: 32,
    featured: true,
    description: "React foam midsole, air cushioning, breathable mesh upper for long-distance runs.",
    images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80"],
    rating: 4.8,
    numReviews: 302,
    isActive: true,
  },
];

async function seed() {
  try {
    await mongoose.connect(MONGO_URI);
    console.log("✅ Connected to MongoDB");

    // Remove existing seeded products (optional — comment out to keep existing)
    await Product.deleteMany({ category: { $in: ["Electronics", "Clothing"] } });
    console.log("🗑️  Cleared existing Electronics & Clothing products");

    await Product.insertMany([...electronics, ...clothing]);
    console.log(`✅ Seeded ${electronics.length} Electronics + ${clothing.length} Clothing products`);

    process.exit(0);
  } catch (err) {
    console.error("❌ Seed error:", err);
    process.exit(1);
  }
}

seed();